title: William Russell # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an undergraduate studying Computer Science in Engineering at the University of Michigan 
  <br><br>
  Check out my work on my github or follow me on LinkedIn
  <br><br>
  <a href="https://www.linkedin.com/in/russell-william-aaron">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
